[project]
name = "prolog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "notebook>=7.4.3",
    "pip>=25.1.1",
    "simpful>=2.12.0",
]
